// Generated by ts-to-zod
import { z } from "npm:zod";
import {
  BaseWarranty,
  Battery,
  BundledService,
  Camera,
  CaseMaterial,
  Chipset,
  Color,
  CountryRegion,
  Ethernet,
  FingerprintReader,
  Graphics,
  Keyboard,
  MachineType,
  MediaReader,
  Memory,
  Microphone,
  MonitorCable,
  NFC,
  OperatingSystem,
  PowerAdapter,
  Processor,
  Product,
  Region,
  SmartCardReader,
  Storage,
  SystemManagement,
  TopSeller,
  TPM,
  WLANBluetooth,
  WWAN,
} from "./ThinkPadT480S.ts";

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const countryRegionSchema = z.nativeEnum(CountryRegion);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const topSellerSchema = z.nativeEnum(TopSeller);

export const processorSchema = z.nativeEnum(Processor);

export const graphicsSchema = z.nativeEnum(Graphics);

export const chipsetSchema = z.nativeEnum(Chipset);

export const memorySchema = z.nativeEnum(Memory);

export const storageSchema = z.nativeEnum(Storage);

export const bundledServiceSchema = z.nativeEnum(BundledService);

export const mediaReaderSchema = z.nativeEnum(MediaReader);

export const ethernetSchema = z.nativeEnum(Ethernet);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const wwanSchema = z.nativeEnum(WWAN);

export const smartCardReaderSchema = z.nativeEnum(SmartCardReader);

export const caseMaterialSchema = z.nativeEnum(CaseMaterial);

export const monitorCableSchema = z.nativeEnum(MonitorCable);

export const cameraSchema = z.nativeEnum(Camera);

export const microphoneSchema = z.nativeEnum(Microphone);

export const colorSchema = z.nativeEnum(Color);

export const keyboardSchema = z.nativeEnum(Keyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const nfcSchema = z.nativeEnum(NFC);

export const tpmSchema = z.nativeEnum(TPM);

export const batterySchema = z.nativeEnum(Battery);

export const powerAdapterSchema = z.nativeEnum(PowerAdapter);

export const systemManagementSchema = z.nativeEnum(SystemManagement);

export const operatingSystemSchema = z.nativeEnum(OperatingSystem);

export const baseWarrantySchema = z.nativeEnum(BaseWarranty);

export const thinkPadT480SSchema = z.object({
  Model: z.string(),
  Product: productSchema,
  Region: regionSchema,
  "Country/Region": countryRegionSchema,
  "Machine Type": machineTypeSchema,
  TopSeller: topSellerSchema,
  Processor: processorSchema,
  Graphics: graphicsSchema,
  Chipset: chipsetSchema,
  Memory: memorySchema,
  Storage: storageSchema,
  Display: z.string(),
  Touchscreen: bundledServiceSchema,
  "Media Reader": mediaReaderSchema,
  Ethernet: ethernetSchema,
  Optical: bundledServiceSchema,
  "WLAN + Bluetooth": wLANBluetoothSchema,
  WWAN: wwanSchema,
  "SIM Card": bundledServiceSchema,
  "Smart Card Reader": smartCardReaderSchema,
  "Case Material": caseMaterialSchema,
  "Monitor Cable": monitorCableSchema,
  Camera: cameraSchema,
  Microphone: microphoneSchema,
  Color: colorSchema,
  Keyboard: keyboardSchema,
  "Fingerprint Reader": fingerprintReaderSchema,
  NFC: nfcSchema,
  TPM: tpmSchema,
  Battery: batterySchema,
  "Power Adapter": powerAdapterSchema,
  "System Management": systemManagementSchema,
  "Operating System": operatingSystemSchema,
  "Bundled Software": bundledServiceSchema,
  "Base Warranty": baseWarrantySchema,
  "Bundled Service": bundledServiceSchema,
  "EAN / UPC / JAN": z.string(),
  "End of Support": z.date(),
  "Announce Date": z.date(),
});
