// Generated by ts-to-zod
import { z } from "npm:zod";
import { Product, Region, MachineType, Global, Processor, VPro, Graphics, Memory, Display, MultiTouch, Storage, WLANBluetooth, SIMCard, SmartCardReader, Camera, Keyboard, FingerprintReader, Battery, PowerAdapter, OperatingSystem, Warranty, ANNDateMmYy } from "./ThinkPadX260.ts";

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const globalSchema = z.nativeEnum(Global);

export const processorSchema = z.nativeEnum(Processor);

export const vProSchema = z.nativeEnum(VPro);

export const graphicsSchema = z.nativeEnum(Graphics);

export const memorySchema = z.nativeEnum(Memory);

export const displaySchema = z.nativeEnum(Display);

export const multiTouchSchema = z.nativeEnum(MultiTouch);

export const storageSchema = z.nativeEnum(Storage);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const sIMCardSchema = z.nativeEnum(SIMCard);

export const smartCardReaderSchema = z.nativeEnum(SmartCardReader);

export const cameraSchema = z.nativeEnum(Camera);

export const keyboardSchema = z.nativeEnum(Keyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const batterySchema = z.nativeEnum(Battery);

export const powerAdapterSchema = z.nativeEnum(PowerAdapter);

export const operatingSystemSchema = z.nativeEnum(OperatingSystem);

export const warrantySchema = z.nativeEnum(Warranty);

export const aNNDateMmYySchema = z.nativeEnum(ANNDateMmYy);

export const thinkPadX260Schema = z.object({
    Model: z.string(),
    Product: productSchema,
    Region: regionSchema,
    "Machine Type": machineTypeSchema,
    TopSeller: globalSchema,
    Processor: processorSchema,
    vPro: vProSchema,
    Graphics: graphicsSchema,
    Memory: memorySchema,
    Display: displaySchema,
    "Multi-touch": multiTouchSchema,
    Storage: storageSchema,
    Optical: multiTouchSchema,
    "WLAN + Bluetooth": wLANBluetoothSchema,
    WWAN: multiTouchSchema,
    "SIM Card": sIMCardSchema,
    "Smart Card Reader": smartCardReaderSchema,
    Camera: cameraSchema,
    Keyboard: keyboardSchema,
    "Fingerprint Reader": fingerprintReaderSchema,
    Battery: batterySchema,
    "Power Adapter": powerAdapterSchema,
    "Operating System": operatingSystemSchema,
    Warranty: warrantySchema,
    Global: globalSchema,
    "Ann Date (mm/yy)": aNNDateMmYySchema
});
