// Generated by ts-to-zod
import { z } from "npm:zod";
import { Product, Region, MachineType, TopSeller, Processor, VPro, Graphics, Chipset, Memory, Display, MonitorCable, Storage, WLANBluetooth, WWAN, SIMCard, SmartCardReader, Camera, Keyboard, FingerprintReader, TPM, Battery, PowerAdapter, OperatingSystem, Warranty, ANNDateMmYy } from "../schemas/ThinkPadT470P.ts";

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const topSellerSchema = z.nativeEnum(TopSeller);

export const processorSchema = z.nativeEnum(Processor);

export const vProSchema = z.nativeEnum(VPro);

export const graphicsSchema = z.nativeEnum(Graphics);

export const chipsetSchema = z.nativeEnum(Chipset);

export const memorySchema = z.nativeEnum(Memory);

export const displaySchema = z.nativeEnum(Display);

export const monitorCableSchema = z.nativeEnum(MonitorCable);

export const storageSchema = z.nativeEnum(Storage);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const wwanSchema = z.nativeEnum(WWAN);

export const sIMCardSchema = z.nativeEnum(SIMCard);

export const smartCardReaderSchema = z.nativeEnum(SmartCardReader);

export const cameraSchema = z.nativeEnum(Camera);

export const keyboardSchema = z.nativeEnum(Keyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const tpmSchema = z.nativeEnum(TPM);

export const batterySchema = z.nativeEnum(Battery);

export const powerAdapterSchema = z.nativeEnum(PowerAdapter);

export const operatingSystemSchema = z.nativeEnum(OperatingSystem);

export const warrantySchema = z.nativeEnum(Warranty);

export const aNNDateMmYySchema = z.nativeEnum(ANNDateMmYy);

export const thinkPadT470PSchema = z.object({
    Model: z.string(),
    Product: productSchema,
    Region: regionSchema,
    "Machine Type": machineTypeSchema,
    TopSeller: topSellerSchema,
    Processor: processorSchema,
    vPro: vProSchema,
    Graphics: graphicsSchema,
    Chipset: chipsetSchema,
    Memory: memorySchema,
    Display: displaySchema,
    "Multi-touch": monitorCableSchema,
    Storage: storageSchema,
    Optical: monitorCableSchema,
    "WLAN + Bluetooth": wLANBluetoothSchema,
    WWAN: wwanSchema,
    "SIM Card": sIMCardSchema,
    "Smart Card Reader": smartCardReaderSchema,
    "Monitor Cable": monitorCableSchema,
    Camera: cameraSchema,
    Keyboard: keyboardSchema,
    "Fingerprint Reader": fingerprintReaderSchema,
    NFC: monitorCableSchema,
    TPM: tpmSchema,
    Battery: batterySchema,
    "Power Adapter": powerAdapterSchema,
    "Operating System": operatingSystemSchema,
    Warranty: warrantySchema,
    "Ann Date (mm/yy)": aNNDateMmYySchema
});
