// Generated by ts-to-zod
import { z } from "zod";
import { Product, Region, MachineType, TopSeller, Processor, VPro, Graphics, Memory, Display, Storage, Optical, WLANBluetooth, NFC, SIMCard, SmartCardReader, Camera, BacklitKeyboard, FingerprintReader, BatteryCells, PowerAdapterWatt, Preload, BaseWarranty, Global } from "./data/schemas/ThinkPad_T440p";

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const topSellerSchema = z.nativeEnum(TopSeller);

export const processorSchema = z.nativeEnum(Processor);

export const vProSchema = z.nativeEnum(VPro);

export const graphicsSchema = z.nativeEnum(Graphics);

export const memorySchema = z.nativeEnum(Memory);

export const displaySchema = z.nativeEnum(Display);

export const storageSchema = z.nativeEnum(Storage);

export const opticalSchema = z.nativeEnum(Optical);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const nfcSchema = z.nativeEnum(NFC);

export const sIMCardSchema = z.nativeEnum(SIMCard);

export const smartCardReaderSchema = z.nativeEnum(SmartCardReader);

export const cameraSchema = z.nativeEnum(Camera);

export const backlitKeyboardSchema = z.nativeEnum(BacklitKeyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const batteryCellsSchema = z.nativeEnum(BatteryCells);

export const powerAdapterWattSchema = z.nativeEnum(PowerAdapterWatt);

export const preloadSchema = z.nativeEnum(Preload);

export const baseWarrantySchema = z.nativeEnum(BaseWarranty);

export const globalSchema = z.nativeEnum(Global);

export const thinkPadT440PSchema = z.object({
    Model: z.string(),
    Product: productSchema,
    Region: regionSchema,
    "Machine Type": machineTypeSchema,
    TopSeller: topSellerSchema,
    Processor: processorSchema,
    vPro: vProSchema,
    Graphics: graphicsSchema,
    Memory: memorySchema,
    Display: displaySchema,
    Storage: storageSchema,
    Optical: opticalSchema,
    "WLAN & Bluetooth": wLANBluetoothSchema,
    "WWAN / M.2 SSD": nfcSchema,
    "SIM Card": sIMCardSchema,
    "Smart Card Reader": smartCardReaderSchema,
    Camera: cameraSchema,
    "Backlit Keyboard": backlitKeyboardSchema,
    "Fingerprint Reader": fingerprintReaderSchema,
    NFC: nfcSchema,
    "Battery Cells": batteryCellsSchema,
    "Power Adapter (watt)": powerAdapterWattSchema,
    Preload: preloadSchema,
    "Base Warranty": baseWarrantySchema,
    Global: globalSchema,
    "Ann Date (mm/yy)": z.string()
});
