// Generated by ts-to-zod
import { z } from 'npm:zod';
import {
  BaseWarranty,
  Battery,
  BundledService,
  BundledSoftware,
  Camera,
  CaseMaterial,
  Chipset,
  Color,
  Display,
  Ethernet,
  FingerprintReader,
  Graphics,
  Keyboard,
  MachineType,
  MediaReader,
  Memory,
  Microphone,
  MonitorCable,
  NFC,
  OperatingSystem,
  PowerAdapter,
  Processor,
  Product,
  Region,
  SmartCardReader,
  Storage,
  SystemManagement,
  TopSeller,
  Touchscreen,
  TPM,
  WLANBluetooth,
  WWAN,
} from './ThinkPadT480.ts';

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const topSellerSchema = z.nativeEnum(TopSeller);

export const processorSchema = z.nativeEnum(Processor);

export const graphicsSchema = z.nativeEnum(Graphics);

export const chipsetSchema = z.nativeEnum(Chipset);

export const memorySchema = z.nativeEnum(Memory);

export const storageSchema = z.nativeEnum(Storage);

export const bundledSoftwareSchema = z.nativeEnum(BundledSoftware);

export const displaySchema = z.nativeEnum(Display);

export const touchscreenSchema = z.nativeEnum(Touchscreen);

export const mediaReaderSchema = z.nativeEnum(MediaReader);

export const ethernetSchema = z.nativeEnum(Ethernet);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const wwanSchema = z.nativeEnum(WWAN);

export const smartCardReaderSchema = z.nativeEnum(SmartCardReader);

export const monitorCableSchema = z.nativeEnum(MonitorCable);

export const caseMaterialSchema = z.nativeEnum(CaseMaterial);

export const cameraSchema = z.nativeEnum(Camera);

export const microphoneSchema = z.nativeEnum(Microphone);

export const colorSchema = z.nativeEnum(Color);

export const keyboardSchema = z.nativeEnum(Keyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const nfcSchema = z.nativeEnum(NFC);

export const tpmSchema = z.nativeEnum(TPM);

export const batterySchema = z.nativeEnum(Battery);

export const powerAdapterSchema = z.nativeEnum(PowerAdapter);

export const systemManagementSchema = z.nativeEnum(SystemManagement);

export const operatingSystemSchema = z.nativeEnum(OperatingSystem);

export const baseWarrantySchema = z.nativeEnum(BaseWarranty);

export const bundledServiceSchema = z.nativeEnum(BundledService);

export const thinkPadT480Schema = z.object({
  Model: z.string(),
  Product: productSchema,
  Region: regionSchema,
  'Country/Region': z.string(),
  'Machine Type': machineTypeSchema,
  TopSeller: topSellerSchema,
  Processor: processorSchema,
  Graphics: graphicsSchema,
  Chipset: chipsetSchema,
  Memory: memorySchema,
  Storage: storageSchema,
  'Optane Memory': bundledSoftwareSchema,
  Display: displaySchema,
  Touchscreen: touchscreenSchema,
  'Media Reader': mediaReaderSchema,
  Ethernet: ethernetSchema,
  Optical: bundledSoftwareSchema,
  'WLAN + Bluetooth': wLANBluetoothSchema,
  WWAN: wwanSchema,
  'SIM Card': bundledSoftwareSchema,
  'Smart Card Reader': smartCardReaderSchema,
  'Monitor Cable': monitorCableSchema,
  'Case Material': caseMaterialSchema,
  Camera: cameraSchema,
  Microphone: microphoneSchema,
  Color: colorSchema,
  Keyboard: keyboardSchema,
  'Fingerprint Reader': fingerprintReaderSchema,
  NFC: nfcSchema,
  TPM: tpmSchema,
  Battery: batterySchema,
  'Power Adapter': powerAdapterSchema,
  'System Management': systemManagementSchema,
  'Operating System': operatingSystemSchema,
  'Bundled Software': bundledSoftwareSchema,
  'Base Warranty': baseWarrantySchema,
  'Bundled Service': bundledServiceSchema,
  'EAN / UPC / JAN': z.string(),
  'End of Support': z.string(),
  'Announce Date': z.date(),
});
