// Generated by ts-to-zod
import { z } from "zod";
import { Product, Region, MachineType, TopSeller, Processor, VPro, Graphics, Memory, Display, MultiTouch, Storage, WLANBluetooth, WWANM2SSD, SIMCard, SmartCardReaderM2SSD, Camera, BacklitKeyboard, FingerprintReader, NFC, BatteryCellsInternalExternal, PowerAdapterWatt, Preload, BaseWarranty, Global, ANNDateMmYy } from "./data/schemas/ThinkPadX240";

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const topSellerSchema = z.nativeEnum(TopSeller);

export const processorSchema = z.nativeEnum(Processor);

export const vProSchema = z.nativeEnum(VPro);

export const graphicsSchema = z.nativeEnum(Graphics);

export const memorySchema = z.nativeEnum(Memory);

export const displaySchema = z.nativeEnum(Display);

export const multiTouchSchema = z.nativeEnum(MultiTouch);

export const storageSchema = z.nativeEnum(Storage);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const wwanm2ssdSchema = z.nativeEnum(WWANM2SSD);

export const sIMCardSchema = z.nativeEnum(SIMCard);

export const smartCardReaderM2SSDSchema = z.nativeEnum(SmartCardReaderM2SSD);

export const cameraSchema = z.nativeEnum(Camera);

export const backlitKeyboardSchema = z.nativeEnum(BacklitKeyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const nfcSchema = z.nativeEnum(NFC);

export const batteryCellsInternalExternalSchema = z.nativeEnum(BatteryCellsInternalExternal);

export const powerAdapterWattSchema = z.nativeEnum(PowerAdapterWatt);

export const preloadSchema = z.nativeEnum(Preload);

export const baseWarrantySchema = z.nativeEnum(BaseWarranty);

export const globalSchema = z.nativeEnum(Global);

export const aNNDateMmYySchema = z.nativeEnum(ANNDateMmYy);

export const thinkPadX240Schema = z.object({
    Model: z.string(),
    Product: productSchema,
    Region: regionSchema,
    "Machine Type": machineTypeSchema,
    TopSeller: topSellerSchema,
    Processor: processorSchema,
    vPro: vProSchema,
    Graphics: graphicsSchema,
    Memory: memorySchema,
    Display: displaySchema,
    "Multi-touch": multiTouchSchema,
    Storage: storageSchema,
    Optical: multiTouchSchema,
    "WLAN & Bluetooth": wLANBluetoothSchema,
    "WWAN / M.2 SSD": wwanm2ssdSchema,
    "SIM Card": sIMCardSchema,
    "Smart Card Reader / M.2 SSD": smartCardReaderM2SSDSchema,
    Camera: cameraSchema,
    "Backlit Keyboard": backlitKeyboardSchema,
    "Fingerprint Reader": fingerprintReaderSchema,
    NFC: nfcSchema,
    "Battery Cells (internal + external)": batteryCellsInternalExternalSchema,
    "Power Adapter (watt)": powerAdapterWattSchema,
    Preload: preloadSchema,
    "Base Warranty": baseWarrantySchema,
    Global: globalSchema,
    "Ann Date (mm/yy)": aNNDateMmYySchema
});
