// Generated by ts-to-zod
import { z } from "zod";
import { Product, Region, CountryRegion, MachineType, TopSeller, Processor, Graphics, Chipset, Memory, Storage, Display, BundledAccessories, MediaReader, Ethernet, WLANBluetooth, WWAN, SIMCard, SmartCardReader, MonitorCable, CaseMaterial, Camera, Microphone, Color, Keyboard, FingerprintReader, NFC, TPM, Battery, PowerAdapter, SystemManagement, BundledSoftware, BaseWarranty } from "./data/schemas/ThinkPadX270";

export const productSchema = z.nativeEnum(Product);

export const regionSchema = z.nativeEnum(Region);

export const countryRegionSchema = z.nativeEnum(CountryRegion);

export const machineTypeSchema = z.nativeEnum(MachineType);

export const topSellerSchema = z.nativeEnum(TopSeller);

export const processorSchema = z.nativeEnum(Processor);

export const graphicsSchema = z.nativeEnum(Graphics);

export const chipsetSchema = z.nativeEnum(Chipset);

export const memorySchema = z.nativeEnum(Memory);

export const storageSchema = z.nativeEnum(Storage);

export const displaySchema = z.nativeEnum(Display);

export const bundledAccessoriesSchema = z.nativeEnum(BundledAccessories);

export const mediaReaderSchema = z.nativeEnum(MediaReader);

export const ethernetSchema = z.nativeEnum(Ethernet);

export const wLANBluetoothSchema = z.nativeEnum(WLANBluetooth);

export const wwanSchema = z.nativeEnum(WWAN);

export const sIMCardSchema = z.nativeEnum(SIMCard);

export const smartCardReaderSchema = z.nativeEnum(SmartCardReader);

export const monitorCableSchema = z.nativeEnum(MonitorCable);

export const caseMaterialSchema = z.nativeEnum(CaseMaterial);

export const cameraSchema = z.nativeEnum(Camera);

export const microphoneSchema = z.nativeEnum(Microphone);

export const colorSchema = z.nativeEnum(Color);

export const keyboardSchema = z.nativeEnum(Keyboard);

export const fingerprintReaderSchema = z.nativeEnum(FingerprintReader);

export const nfcSchema = z.nativeEnum(NFC);

export const tpmSchema = z.nativeEnum(TPM);

export const batterySchema = z.nativeEnum(Battery);

export const powerAdapterSchema = z.nativeEnum(PowerAdapter);

export const systemManagementSchema = z.nativeEnum(SystemManagement);

export const bundledSoftwareSchema = z.nativeEnum(BundledSoftware);

export const baseWarrantySchema = z.nativeEnum(BaseWarranty);

export const thinkPadX270Schema = z.object({
    Model: z.string(),
    Product: productSchema,
    Region: regionSchema,
    "Country/Region": countryRegionSchema,
    "Machine Type": machineTypeSchema,
    TopSeller: topSellerSchema,
    Processor: processorSchema,
    Graphics: graphicsSchema,
    Chipset: chipsetSchema,
    Memory: memorySchema,
    Storage: storageSchema,
    Display: displaySchema,
    Touchscreen: bundledAccessoriesSchema,
    "Media Reader": mediaReaderSchema,
    Ethernet: ethernetSchema,
    Optical: bundledAccessoriesSchema,
    "WLAN + Bluetooth": wLANBluetoothSchema,
    WWAN: wwanSchema,
    "SIM Card": sIMCardSchema,
    "Smart Card Reader": smartCardReaderSchema,
    "Monitor Cable": monitorCableSchema,
    "Bundled Accessories": bundledAccessoriesSchema,
    "Case Material": caseMaterialSchema,
    Camera: cameraSchema,
    Microphone: microphoneSchema,
    Docking: bundledAccessoriesSchema,
    Color: colorSchema,
    Keyboard: keyboardSchema,
    "Fingerprint Reader": fingerprintReaderSchema,
    NFC: nfcSchema,
    TPM: tpmSchema,
    Battery: batterySchema,
    "Power Adapter": powerAdapterSchema,
    "System Management": systemManagementSchema,
    "Operating System": z.string(),
    "Bundled Software": bundledSoftwareSchema,
    "Base Warranty": baseWarrantySchema,
    "Bundled Service": bundledAccessoriesSchema,
    "EAN / UPC / JAN": z.string(),
    "End of Support": z.date(),
    "Announce Date": z.date()
});
